CREATE TABLE "T_CARPOOL"
(
	"CARPOOL_ID" NUMBER NOT NULL,
	"OWNER" NUMBER NOT NULL,
	"CAR_TYPE" VARCHAR2(40 BYTE),
	"ORIGIN" VARCHAR2(40 BYTE),
	"DESTINATION" VARCHAR2(40 BYTE),
	"VIA" VARCHAR2(40 BYTE),
	"NUMBER_OF_SEATS" NUMBER NOT NULL,
	"ALREADY_ALLOCATED" NUMBER NOT NULL,
	"AMOUNT_FOR_JOURNEY" NUMBER NOT NULL,
	"VERSION" NUMBER NOT NULL,
    "CREATED_DATE" DATE DEFAULT sysdate NOT NULL,
    "LAST_MODIFIED_DATE" DATE,
    CONSTRAINT "T_CARPOOL_PK" PRIMARY KEY ("CARPOOL_ID")
);