CREATE TABLE "CARPOOL"
(
	"CARPOOL_ID" NUMBER NOT NULL,
	"LAST_FOUR" NUMBER NOT NULL,
	"TYPE" NUMBER NOT NULL,
	"STATUS" NUMBER NOT NULL,
	"AMOUNT" NUMBER NOT NULL,
	"REQUESTED_TIME" DATE NOT NULL,
	"RESPONSE_TIME" DATE,
	"RESPONSE_LOG" VARCHAR2(400 BYTE),
	"VERSION" NUMBER NOT NULL,
    "CREATED_DATE" DATE DEFAULT sysdate NOT NULL,
    "LAST_MODIFIED_DATE" DATE,
    CONSTRAINT "T_CC_REQUEST_PK" PRIMARY KEY ("CC_REQUEST_ID")
);